 
services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    networks:
    - asa-network
    
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./proxy/certificados:/etc/nginx/certificados
    networks:
      - asa-network

  ssh:
    build: 
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh
    ports:
      - "22:22"
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge
  