
services:
  # Serviço SSH
  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh-cliente1
    ports:
      - "2021:22"
    networks:
      - provedor_asa-network

  # Serviço de banco de dados
  db_miami:
    image: mariadb:latest
    container_name: db_miami
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - provedor_asa-network

  miami1:
    image: wordpress:latest
    container_name: miami1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_miami
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - provedor_asa-network

  miami2:
    image: wordpress:latest
    container_name: miami2
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_miami
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - provedor_asa-network


volumes:
  db_data: {}  # Volume persistente para o banco de dados
  wp_data: {}  # Volume persistente para os dados do WordPress

# Docker Networks
networks:
  provedor_asa-network:
    external: true  # Caso a rede externa não exista, remova essa linha para o Docker Compose gerenciar
